/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package adisuper94.ids.hashtable;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class IDSHashtableTest {
  @Test
  void someLibraryMethodReturnsTrue() {
    IDSHashtable classUnderTest = new IDSHashtable(10, 2, 2);
    classUnderTest.recordFlow(1);
    classUnderTest.recordFlow(1);
    assertEquals(2, classUnderTest.getCount(1));

    for (int i = 0; i < 1000; i++) {
      classUnderTest.recordFlow(i);
    }
  }
}
